### ISSUE TITLE
Console Issues

### ISSUE THREAD

**Issue by efox3590** [chickenricer/instagrammer#14]
This is what I get upon logging in:

<img width="513" alt="screen shot 2017-04-23 at 10 39 03 am" src="https://cloud.githubusercontent.com/assets/24904439/25314400/20aaaa68-2811-11e7-9066-dcbf36844323.png">

**Comment by chickenricer** [comment]
I haven't locked down the function and routes yet which is why it's throwing those errors, but if you go ahead and register/login the functionality works. Will address those errors in the future. One thing at a time. :)
